# Generated by Django 5.2.5 on 2025-10-02 01:47

import django.db.models.deletion
import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=submissions.models.submission_upload_path)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.student')),
            ],
            options={
                'indexes': [models.Index(fields=['assignment', 'student'], name='submissions_assignm_3561bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='uq_submission_assignment_student')],
            },
        ),
    ]
