# Generated by Django 5.2.5 on 2025-10-02 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='users.lecturer')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='courses_cou_title_6e78a2_idx')],
            },
        ),
    ]
