# Generated by Django 5.2.5 on 2025-09-30 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lecturer', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='courses_cou_title_6e78a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'indexes': [models.Index(fields=['course', 'due_date'], name='courses_ass_course__1c7acb_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'title'), name='uq_assignment_course_title')],
            },
        ),
    ]
