# Generated by Django 5.2.5 on 2025-09-30 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
