# Generated by Django 5.2.5 on 2025-10-02 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'indexes': [models.Index(fields=['course', 'due_date'], name='assignments_course__2d636b_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'title'), name='uq_assignment_course_title')],
            },
        ),
    ]
